use axum::{
    extract::{Path, State},
    http::StatusCode,
    Json,
};
use serde::{Deserialize, Serialize};
use sqlx::Row;
use tracing::{error, info, warn};

use super::error::AppError;
use super::AppState;

// ─── DTOs ──────────────────────────────────────────────────

/// A local DNS A record managed by Panoptikon.
#[derive(Debug, Serialize)]
pub struct UnboundDnsRecord {
    pub id: String,
    pub hostname: String,
    pub ip_address: String,
    pub enabled: bool,
    pub created_at: String,
    pub updated_at: String,
}

/// Request body for creating / updating a DNS record.
#[derive(Debug, Deserialize)]
pub struct UnboundDnsRecordRequest {
    pub hostname: String,
    pub ip_address: String,
}

/// Response for the "Test Connection" button.
#[derive(Debug, Serialize)]
pub struct UnboundTestConnectionResponse {
    pub success: bool,
    pub message: String,
}

// ─── Helpers ────────────────────────────────────────────────

/// Read a setting from the database.
async fn get_setting(state: &AppState, key: &str) -> Option<String> {
    sqlx::query_scalar::<_, String>("SELECT value FROM settings WHERE key = ?")
        .bind(key)
        .fetch_optional(&state.db)
        .await
        .ok()
        .flatten()
        .filter(|v| !v.is_empty())
}

/// Get the unbound-control socket path from settings.
async fn unbound_control_path(state: &AppState) -> String {
    get_setting(state, "unbound_control_path")
        .await
        .unwrap_or_else(|| "/var/run/unbound.ctl".to_string())
}

/// Generate the Unbound local-data config and write it to the conf file,
/// then reload Unbound.
async fn sync_to_unbound(state: &AppState) {
    let records: Vec<(String, String)> = match sqlx::query_as(
        "SELECT hostname, ip_address FROM unbound_dns_records WHERE enabled = 1 ORDER BY hostname",
    )
    .fetch_all(&state.db)
    .await
    {
        Ok(rows) => rows,
        Err(e) => {
            error!("Failed to load DNS records for Unbound sync: {e}");
            return;
        }
    };

    // Build the config file content.
    let mut conf = String::from(
        "# Auto-generated by Panoptikon — do not edit manually.\n\
         # Changes will be overwritten on next DNS record update.\n\
         server:\n",
    );

    for (hostname, ip) in &records {
        // Ensure the hostname ends with a dot for FQDN.
        let fqdn = if hostname.ends_with('.') {
            hostname.clone()
        } else {
            format!("{hostname}.")
        };
        conf.push_str(&format!("    local-data: \"{fqdn} A {ip}\"\n"));
    }

    // Write the config file.
    let conf_path = "/etc/unbound/unbound.conf.d/panoptikon-local.conf";
    match tokio::fs::write(conf_path, &conf).await {
        Ok(()) => {
            info!(
                "Wrote Unbound config ({} records) to {conf_path}",
                records.len()
            );
        }
        Err(e) => {
            warn!("Failed to write Unbound config to {conf_path}: {e}");
            return;
        }
    }

    // Reload Unbound.
    let ctl_path = unbound_control_path(state).await;
    match tokio::process::Command::new("unbound-control")
        .args(["-s", &ctl_path, "reload"])
        .output()
        .await
    {
        Ok(output) if output.status.success() => {
            info!("Unbound reloaded successfully");
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            warn!("unbound-control reload failed: {stderr}");
        }
        Err(e) => {
            warn!("Failed to run unbound-control: {e}");
        }
    }
}

/// Fetch a single DNS record by ID.
async fn fetch_record_by_id(state: &AppState, id: &str) -> Result<UnboundDnsRecord, AppError> {
    let row = sqlx::query(
        "SELECT id, hostname, ip_address, enabled, created_at, updated_at \
         FROM unbound_dns_records WHERE id = ?",
    )
    .bind(id)
    .fetch_optional(&state.db)
    .await
    .map_err(|e| {
        error!("Failed to fetch DNS record: {e}");
        AppError::Internal(e.to_string())
    })?
    .ok_or(AppError::NotFound)?;

    Ok(UnboundDnsRecord {
        id: row.get("id"),
        hostname: row.get("hostname"),
        ip_address: row.get("ip_address"),
        enabled: row.get::<i32, _>("enabled") != 0,
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
    })
}

// ─── Handlers ──────────────────────────────────────────────

/// GET /api/v1/unbound/dns-records — list all DNS records.
pub async fn list(State(state): State<AppState>) -> Result<Json<Vec<UnboundDnsRecord>>, AppError> {
    let rows = sqlx::query(
        "SELECT id, hostname, ip_address, enabled, created_at, updated_at \
         FROM unbound_dns_records ORDER BY hostname",
    )
    .fetch_all(&state.db)
    .await
    .map_err(|e| {
        error!("Failed to list DNS records: {e}");
        AppError::Internal(e.to_string())
    })?;

    let records: Vec<UnboundDnsRecord> = rows
        .into_iter()
        .map(|r| UnboundDnsRecord {
            id: r.get("id"),
            hostname: r.get("hostname"),
            ip_address: r.get("ip_address"),
            enabled: r.get::<i32, _>("enabled") != 0,
            created_at: r.get("created_at"),
            updated_at: r.get("updated_at"),
        })
        .collect();

    Ok(Json(records))
}

/// POST /api/v1/unbound/dns-records — create a new DNS record.
pub async fn create(
    State(state): State<AppState>,
    Json(body): Json<UnboundDnsRecordRequest>,
) -> Result<(StatusCode, Json<UnboundDnsRecord>), AppError> {
    let id = uuid::Uuid::new_v4().to_string();

    sqlx::query("INSERT INTO unbound_dns_records (id, hostname, ip_address) VALUES (?, ?, ?)")
        .bind(&id)
        .bind(&body.hostname)
        .bind(&body.ip_address)
        .execute(&state.db)
        .await
        .map_err(|e| {
            error!("Failed to create DNS record: {e}");
            AppError::Internal(e.to_string())
        })?;

    sync_to_unbound(&state).await;

    let record = fetch_record_by_id(&state, &id).await?;
    Ok((StatusCode::CREATED, Json(record)))
}

/// PUT /api/v1/unbound/dns-records/:id — update a DNS record.
pub async fn update(
    State(state): State<AppState>,
    Path(id): Path<String>,
    Json(body): Json<UnboundDnsRecordRequest>,
) -> Result<Json<UnboundDnsRecord>, AppError> {
    let affected = sqlx::query(
        "UPDATE unbound_dns_records \
         SET hostname = ?, ip_address = ?, updated_at = datetime('now') \
         WHERE id = ?",
    )
    .bind(&body.hostname)
    .bind(&body.ip_address)
    .bind(&id)
    .execute(&state.db)
    .await
    .map_err(|e| {
        error!("Failed to update DNS record: {e}");
        AppError::Internal(e.to_string())
    })?
    .rows_affected();

    if affected == 0 {
        return Err(AppError::NotFound);
    }

    sync_to_unbound(&state).await;

    let record = fetch_record_by_id(&state, &id).await?;
    Ok(Json(record))
}

/// DELETE /api/v1/unbound/dns-records/:id — delete a DNS record.
pub async fn delete(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> Result<StatusCode, AppError> {
    let affected = sqlx::query("DELETE FROM unbound_dns_records WHERE id = ?")
        .bind(&id)
        .execute(&state.db)
        .await
        .map_err(|e| {
            error!("Failed to delete DNS record: {e}");
            AppError::Internal(e.to_string())
        })?
        .rows_affected();

    if affected == 0 {
        return Err(AppError::NotFound);
    }

    sync_to_unbound(&state).await;

    Ok(StatusCode::NO_CONTENT)
}

/// POST /api/v1/unbound/dns-records/:id/toggle — enable/disable a DNS record.
pub async fn toggle(
    State(state): State<AppState>,
    Path(id): Path<String>,
    Json(body): Json<ToggleRequest>,
) -> Result<Json<UnboundDnsRecord>, AppError> {
    let affected = sqlx::query(
        "UPDATE unbound_dns_records SET enabled = ?, updated_at = datetime('now') WHERE id = ?",
    )
    .bind(body.enabled as i32)
    .bind(&id)
    .execute(&state.db)
    .await
    .map_err(|e| {
        error!("Failed to toggle DNS record: {e}");
        AppError::Internal(e.to_string())
    })?
    .rows_affected();

    if affected == 0 {
        return Err(AppError::NotFound);
    }

    sync_to_unbound(&state).await;

    let record = fetch_record_by_id(&state, &id).await?;
    Ok(Json(record))
}

/// POST /api/v1/unbound/test-connection — test unbound-control connectivity.
pub async fn test_connection(State(state): State<AppState>) -> Json<UnboundTestConnectionResponse> {
    let ctl_path = unbound_control_path(&state).await;

    match tokio::process::Command::new("unbound-control")
        .args(["-s", &ctl_path, "status"])
        .output()
        .await
    {
        Ok(output) if output.status.success() => {
            let stdout = String::from_utf8_lossy(&output.stdout);
            let version_line = stdout
                .lines()
                .find(|l| l.starts_with("version:"))
                .map(|l| l.trim().to_string())
                .unwrap_or_default();
            Json(UnboundTestConnectionResponse {
                success: true,
                message: format!(
                    "Connected to Unbound via {ctl_path}{}",
                    if version_line.is_empty() {
                        String::new()
                    } else {
                        format!(" ({version_line})")
                    }
                ),
            })
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Json(UnboundTestConnectionResponse {
                success: false,
                message: format!("unbound-control failed: {}", stderr.trim()),
            })
        }
        Err(e) => Json(UnboundTestConnectionResponse {
            success: false,
            message: format!("Failed to run unbound-control: {e}"),
        }),
    }
}

#[derive(Debug, Deserialize)]
pub struct ToggleRequest {
    pub enabled: bool,
}
