use anyhow::Result;
use serde::Deserialize;

/// Agent configuration, loaded from a TOML file.
///
/// Example config.toml:
/// ```toml
/// server_url = "ws://10.10.0.25:8080"
/// api_key = "pnk_a1b2c3d4e5f6..."
/// agent_id = "550e8400-e29b-41d4-a716-446655440000"
/// report_interval_seconds = 30
/// ```
#[derive(Debug, Clone, Deserialize)]
pub struct AgentConfig {
    /// WebSocket URL of the Panoptikon server (e.g., "ws://10.10.0.25:8080").
    pub server_url: String,

    /// API key for authentication (generated by the server).
    pub api_key: String,

    /// Unique agent identifier (UUID, assigned by the server).
    pub agent_id: String,

    /// How often to send reports, in seconds.
    #[serde(default = "default_interval")]
    pub report_interval_secs: u64,
}

fn default_interval() -> u64 {
    30
}

impl AgentConfig {
    /// Load configuration from a TOML file.
    pub fn from_file(path: &str) -> Result<Self> {
        let contents = std::fs::read_to_string(path)
            .map_err(|e| anyhow::anyhow!("Failed to read config file {path}: {e}"))?;
        let config: AgentConfig = toml::from_str(&contents)?;
        Ok(config)
    }
}
