#!/bin/bash
# Auto-generated by maestro pipeline — verification commands for this task
# Run this script to verify all requirements are met.
set -e

echo '=== Project Test Suite ==='
cargo test
make test

echo '=== Requirement Verification ==='
echo 'Requirement 1: All API errors return JSON `{ code, message }` body'
cargo test

echo 'Requirement 2: Scan results committed atomically'
echo 'WARN: Run tests in web/tests/e2e/device-scan-no-404.spec.ts'

echo 'Requirement 3: Agent CPU usage during collection significantly reduced'
echo 'WARN: Run tests in web/e2e/agents.spec.ts'

echo 'All verifications passed.'
